### ISSUE TITLE
Update `bpmn-js` to fix duplicate-packages issue in clients

### ISSUE THREAD

**Issue by boris-petrov** [bpmn-io/form-variable-provider#3]
### Describe the Bug

This package depends on `bpmn-js` version 14 while all the rest of the `bpmn-io` ecosystem use 15. That causes duplicate packages to be bundled in a user's bundle.

### Steps to Reproduce

Just install `camunda-bpmn-js`.

### Expected Behavior

`bpmn-js` 15 to be used from everywhere.

### Environment

- Host (Browser/Node version), if applicable:N/A
- OS: Linux
- Library version: 1.1.0

**Comment by marstamm** [comment]
Will be addressed as part of https://github.com/bpmn-io/form-variable-provider/pull/4
